# Generated by Django 5.1.6 on 2025-02-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data criacao"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data atualizacao"
                    ),
                ),
                ("activated", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Estoque")),
                (
                    "image",
                    models.ImageField(
                        height_field=124,
                        upload_to="core/produtos/%y/%m/%d",
                        verbose_name="Imagem",
                        width_field=124,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
